### PR TITLE
Create swd7.md.j2

### PR DESCRIPTION
**Pull request by agdturner**
Init

### CODE REVIEW

**Review by agdturner — COMMENTED** [review]
Init looks fine.

**Review by sharriet — APPROVED** [review]
Fine

**Review by sharriet — APPROVED** [review]
Approved

**Review by sharriet — APPROVED** [review]
Approved again!

**Review by sharriet — APPROVED** [review]
Approved

**Review by sharriet — APPROVED** [review]
Try again...

**Pull request closed without merging**
